[env:gitmate]
platform = espressif32@6.5.0
board = esp32-s3-devkitc-1
framework = arduino
monitor_speed = 115200
upload_speed = 921600
board_build.mcu = esp32s3
board_build.f_cpu = 240000000L
board_build.arduino.memory_type = qio_opi

; Point to local libraries folder
lib_extra_dirs = libraries

; Build flags
build_flags = 
    -D LV_CONF_INCLUDE_SIMPLE
    -D ARDUINO_USB_MODE=1
    -D ARDUINO_USB_CDC_ON_BOOT=1
    -I .

; Use current directory for source files
[platformio]
src_dir = .
include_dir = .
