// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.5.4
// LVGL version: 8.3.6
// Project name: SquareLine_Project

#include "ui.h"

// COMPONENT Benzintro

lv_obj_t * ui_Benzintro_create(lv_obj_t * comp_parent)
{

    lv_obj_t * cui_Benzintro;
    cui_Benzintro = lv_img_create(comp_parent);
    lv_obj_set_width(cui_Benzintro, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(cui_Benzintro, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(cui_Benzintro, LV_ALIGN_CENTER);
    lv_obj_add_flag(cui_Benzintro, LV_OBJ_FLAG_ADV_HITTEST);     /// Flags
    lv_obj_clear_flag(cui_Benzintro, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_img_set_zoom(cui_Benzintro, 110);
    lv_obj_set_style_bg_color(cui_Benzintro, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(cui_Benzintro, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_grad_color(cui_Benzintro, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_img_recolor(cui_Benzintro, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_img_recolor_opa(cui_Benzintro, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    lv_obj_t * cui_ImgButton2;
    cui_ImgButton2 = lv_imgbtn_create(cui_Benzintro);
    lv_obj_set_width(cui_ImgButton2, 64);
    lv_obj_set_height(cui_ImgButton2, 64);
    lv_obj_set_align(cui_ImgButton2, LV_ALIGN_CENTER);

    lv_obj_t ** children = lv_mem_alloc(sizeof(lv_obj_t *) * _UI_COMP_BENZINTRO_NUM);
    children[UI_COMP_BENZINTRO_BENZINTRO] = cui_Benzintro;
    children[UI_COMP_BENZINTRO_IMGBUTTON2] = cui_ImgButton2;
    lv_obj_add_event_cb(cui_Benzintro, get_component_child_event_cb, LV_EVENT_GET_COMP_CHILD, children);
    lv_obj_add_event_cb(cui_Benzintro, del_component_child_event_cb, LV_EVENT_DELETE, children);
    ui_comp_Benzintro_create_hook(cui_Benzintro);
    return cui_Benzintro;
}

