// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.5.4
// LVGL version: 8.3.6
// Project name: SquareLine_Project

#ifndef _UI_COMP_BENZINTRO_H
#define _UI_COMP_BENZINTRO_H

#include "ui.h"

#ifdef __cplusplus
extern "C" {
#endif

// COMPONENT Benzintro
#define UI_COMP_BENZINTRO_BENZINTRO 0
#define UI_COMP_BENZINTRO_IMGBUTTON2 1
#define _UI_COMP_BENZINTRO_NUM 2
lv_obj_t * ui_Benzintro_create(lv_obj_t * comp_parent);

#ifdef __cplusplus
} /*extern "C"*/
#endif

#endif
