// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.5.4
// LVGL version: 8.3.6
// Project name: SquareLine_Project

#ifndef _UI_COMP_IMAGE4_H
#define _UI_COMP_IMAGE4_H

#include "ui.h"

#ifdef __cplusplus
extern "C" {
#endif

// COMPONENT Image4
#define UI_COMP_IMAGE4_IMAGE4 0
#define _UI_COMP_IMAGE4_NUM 1
lv_obj_t * ui_Image4_create(lv_obj_t * comp_parent);

#ifdef __cplusplus
} /*extern "C"*/
#endif

#endif
