// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.5.4
// LVGL version: 8.3.6
// Project name: SquareLine_Project

#include "ui.h"

// COMPONENT Image4

lv_obj_t * ui_Image4_create(lv_obj_t * comp_parent)
{

    lv_obj_t * cui_Image4;
    cui_Image4 = lv_img_create(comp_parent);
    lv_obj_set_width(cui_Image4, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(cui_Image4, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(cui_Image4, lv_pct(1));
    lv_obj_set_y(cui_Image4, lv_pct(1));
    lv_obj_set_align(cui_Image4, LV_ALIGN_CENTER);
    lv_obj_add_flag(cui_Image4, LV_OBJ_FLAG_ADV_HITTEST);     /// Flags
    lv_obj_clear_flag(cui_Image4, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_img_set_zoom(cui_Image4, 1000);

    lv_obj_t ** children = lv_mem_alloc(sizeof(lv_obj_t *) * _UI_COMP_IMAGE4_NUM);
    children[UI_COMP_IMAGE4_IMAGE4] = cui_Image4;
    lv_obj_add_event_cb(cui_Image4, get_component_child_event_cb, LV_EVENT_GET_COMP_CHILD, children);
    lv_obj_add_event_cb(cui_Image4, del_component_child_event_cb, LV_EVENT_DELETE, children);
    ui_comp_Image4_create_hook(cui_Image4);
    return cui_Image4;
}

