// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.5.4
// LVGL version: 8.3.6
// Project name: SquareLine_Project

#include "ui.h"

lv_obj_t * uic_Image2;
lv_obj_t * ui_Screen0 = NULL;
lv_obj_t * ui_Image2 = NULL;
// event funtions

// build funtions

void ui_Screen0_screen_init(void)
{
    ui_Screen0 = lv_obj_create(NULL);
    lv_obj_clear_flag(ui_Screen0, LV_OBJ_FLAG_CLICKABLE | LV_OBJ_FLAG_PRESS_LOCK | LV_OBJ_FLAG_SCROLLABLE |
                      LV_OBJ_FLAG_SCROLL_ELASTIC | LV_OBJ_FLAG_SCROLL_MOMENTUM);     /// Flags
    lv_obj_set_style_bg_color(ui_Screen0, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_Screen0, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Image2 = lv_img_create(ui_Screen0);
    lv_img_set_src(ui_Image2, &ui_img_451643215);
    lv_obj_set_width(ui_Image2, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Image2, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_Image2, 2);
    lv_obj_set_y(ui_Image2, -6);
    lv_obj_set_align(ui_Image2, LV_ALIGN_CENTER);
    lv_obj_add_state(ui_Image2, LV_STATE_PRESSED);       /// States
    lv_obj_add_flag(ui_Image2, LV_OBJ_FLAG_ADV_HITTEST);     /// Flags
    lv_obj_clear_flag(ui_Image2, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_img_set_zoom(ui_Image2, 100);

    uic_Image2 = ui_Image2;

}

void ui_Screen0_screen_destroy(void)
{
    if(ui_Screen0) lv_obj_del(ui_Screen0);

    // NULL screen variables
    ui_Screen0 = NULL;
    uic_Image2 = NULL;
    ui_Image2 = NULL;

}
